const cats = {
  cats: [
    {
      id: 1,
      name: 'Whiskers',
      description: 'A fluffy orange tabby cat.',
      image_url: 'https://uploads.dailydot.com/2018/10/olli-the-polite-cat.jpg',
      age: 3.5,
      personality: 'Playful and friendly',
      sex: 'male',
      health_state: 'excellent',
      is_available: true,
      added_at: '2023-01-15T14:30:00Z',
      updated_at: null,
    },
    {
      id: 2,
      name: 'Luna',
      description: 'A sleek black cat with green eyes.',
      image_url: 'https://uploads.dailydot.com/2018/10/olli-the-polite-cat.jpg',
      age: 2.0,
      personality: 'Calm and independent',
      sex: 'female',
      health_state: 'medium',
      is_available: true,
      added_at: '2023-02-10T11:45:00Z',
      updated_at: '2023-04-05T09:15:00Z',
    },
    {
      id: 3,
      name: 'Oscar',
      description: 'A chubby gray cat with a playful spirit.',
      image_url: 'https://uploads.dailydot.com/2018/10/olli-the-polite-cat.jpg',
      age: 5.0,
      personality: 'Curious and mischievous',
      sex: 'male',
      health_state: 'poor',
      is_available: false,
      added_at: '2023-03-20T17:20:00Z',
      updated_at: null,
    },
    {
      id: 4,
      name: 'Mittens',
      description: 'A fluffy white cat with blue eyes.',
      image_url: 'https://uploads.dailydot.com/2018/10/olli-the-polite-cat.jpg',
      age: 1.5,
      personality: 'Affectionate and playful',
      sex: 'female',
      health_state: 'excellent',
      is_available: true,
      added_at: '2023-04-01T09:00:00Z',
      updated_at: null,
    },
    {
      id: 5,
      name: 'Leo',
      description: 'A sleek and agile brown tabby cat.',
      image_url: 'https://uploads.dailydot.com/2018/10/olli-the-polite-cat.jpg',
      age: 2.5,
      personality: 'Adventurous and energetic',
      sex: 'male',
      health_state: 'medium',
      is_available: true,
      added_at: '2023-04-10T15:30:00Z',
      updated_at: null,
    },
  ],
};

export default cats;
